name: NuGet Publish

on:
  push:
    branches:
      - master
  workflow_dispatch:
  # all inputs default to push all - if package exists already, it'll be skipped anyway

jobs:
  nuget-publish:
    runs-on: ubuntu-latest

    steps:
      # Prepare environment
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup nuget feed
        run: |
          dotnet nuget add source --username soccerjoshj07 --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github https://nuget.pkg.github.com/soccerjoshj07/index.json
      - name: Install dependencies
        run: dotnet restore
      
      - name: Publish All Nuget Packages
        run: |
          mkdir __out
          dotnet pack -c Release -o __out --no-restore
          dotnet nuget push "./__out/*.nupkg" --skip-duplicate --no-symbols true --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"
